-- MySQL Script generated by MySQL Workbench
-- Thu Apr 21 14:19:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema masterfood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema masterfood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `masterfood` DEFAULT CHARACTER SET utf8 ;
USE `masterfood` ;

-- -----------------------------------------------------
-- Table `masterfood`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masterfood`.`receita` (
  `cod` INT(6) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `ingredientes` TEXT NOT NULL,
  `modo_preparo` TEXT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
